name: GitHub Classroom Workflow

on: 
  push:
    branches:
    - 'main' # add ! to deactivate
    - '!badges'
    - '!feedback'

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build src/src.sln --no-restore          

      # add id to action so outputs can be used
      - name: Autograder
        uses: mikkopa/autograding@v2
        id: autograder
        continue-on-error: true

    outputs:
      grading-score: ${{ steps.autograder.outputs.Points }}
      
      
# job to build custom status badges
  build-badges:
    name: Build Badges
    runs-on: ubuntu-latest
    if: always()
    needs: build
    steps:
      # need to checkout whole repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # switch to badges branch
      - run: git checkout badges || git checkout -b badges

      # make dir for badges
      - name: make badges dir
        run: mkdir -p .github/badges

      # create points bar
      - name: make points bar
        uses: markpatterson27/points-bar@v1
        with:
          points: ${{ needs.build.outputs.grading-score }}
          path: '.github/badges/points-bar.svg'

      # commit and push badge if score has changed
      - name: Commit and push badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '.github/badges'
          git commit -m "Add/Update badge" || exit 0
          git push origin badges
